feat: Add workflow step for conventional release labels
broadinstitute/shared-workflows pull request #108
Opened 2024-12-09 22:24 UTC by tfhartmann

This will add labels based on conventional commit messages, that can be used later in generating releases automatically.

2024-12-09 22:30 UTC, tfhartmann commented
example of what this looks like https://github.com/broadinstitute/kubernetes-atlantis-devnull/pull/65

2024-12-19 21:39 UTC, coreone requested changes

2024-12-19 21:39 UTC, coreone commented on .github/workflows/close-stale.yaml
> +      days_before_issue_stale:
I think you missed adding these inputs to the actual job instead of the hard-coded values that are there now...

2025-01-06 16:24 UTC, coreone approved these changes

2025-01-06 16:25 UTC, merged